apiVersion: v1
kind: Service
metadata:
  name: fiap-techchallenge-service
spec:
  selector:
    app: fiap-techchallenge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer